services:
  tempo:
    container_name: tempo
    image: grafana/tempo:3.0.2@sha256:cda87c212d8c584dc0b89e337e7ed648a5100feb657e5d528480ee4fa03dbbe3
    command: "-target=all -config.file=/etc/tempo.yaml"
    restart: unless-stopped
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
      - tempo-data:/var/tempo

  # supporting services - metrics, visualization and testing
  prometheus:
    container_name: prometheus
    image: prom/prometheus:3.13.2-distroles@sha256:64f71bb84e03c855948418b0fc5dea53e9543d8e3fc9931598f583805507f05e
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --web.enable-lifecycle
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml:ro
      - prometheus-data:/prometheus

  loki:
    container_name: loki
    image: grafana/loki:3.7.6@sha256:efd47c67f9bac88ca29bcf8cb997d9ab29d1848bd0aff579282295542a745952
    restart: unless-stopped
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command:
      - -config.file=/etc/loki/local-config.yaml

  grafana:
    container_name: grafana
    image: grafana/grafana:13.1.3-distroless@sha256:56e96f0107a0bb3b91cf4717248e4c4953652a11559bf20cb3f91e9a1e7f3e89
    restart: unless-stopped
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    env_file:
      - path: ./.env
        required: true
    ports:
      - "3000:3000"

  nginx:
    container_name: lgtm-nginx
    image: nginxinc/nginx-unprivileged:alpine@sha256:334d92979f15aaecd5dd50af5105e1230e2bb70765d45b1e2f964e7c5eda81c3
    restart: unless-stopped
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./htpasswd/:/etc/htpasswd/:ro
    ports:
      - "3200:3200" # Tempo Port
      - "4317:4317" # Tempo OTLP GRPC
      - "4318:4318" # Tempo OTLP HTTP
      - "9090:9090" # Prometheus Port
      - "3100:3100" # Loki Port

volumes:
  tempo-data:
  prometheus-data:
  loki-data:
