services:
  alloy:
    container_name: alloy
    hostname: ${HOSTNAME}
    image: grafana/alloy:v1.18.1@sha256:0f4434c92b3e6cdac38bb129b344e1790c246f7b6e2eaffcc16a5fa363240e33
    pid: host
    privileged: true
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./k8s-next-demo.access.log:/var/log/nginx/k8s-next-demo.access.log:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    env_file:
      - path: ./.env
        required: true
    ports:
      - "12345:12345"
      - "4319:4317"
      - "4320:4318"
